schema_version: 1

context:
  name: pyironflow
  version: 0.1.0
  python_min: '3.11'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pyironflow-${{ version }}.tar.gz
  sha256: d1f4b1cab1e178bc2cf95a12b349e4556ad853a6af23d952bb43c1f03a9ba93d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
    - hatch-jupyter-builder
    - versioneer
    - pip
    - anywidget
    - esbuild
    - ipytree
    - ipython
    - ipywidgets
    - nodejs
    - traitlets
    - pyiron_workflow
  run:
    - python >=${{ python_min }},<3.13
    - anywidget ==0.9.18
    - ipytree ==0.2.2
    - ipython >=9.16.1,<9.17.0
    - ipywidgets >=8.1.8,<8.2.0
    - pyiron_workflow ==0.20.0
    - traitlets >=5.14.3,<5.15.0
tests:
  - python:
      imports:
        - pyironflow
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: react xyflow for pyiron
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/pyiron/pyironFlow

extra:
  recipe-maintainers:
    - pmrv
    - jan-janssen
    - srmnitc
    - liamhuber
